name: CI

on:
  push:
    tags: ["v*"]
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  # PACKAGE: "chimera_server_app"
  # REGISTRY: "ghcr.io"
  # IMAGE_NAME: "clash-rs"
  RUST_LOG: "clash=TRACE"
  # RUST_TOOLCHAIN: "nightly-2025-09-15"
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  CROSS_CONTAINER_UID: 1001
  CROSS_CONTAINER_GID: 118
jobs:
  lint:
    name: Lint (ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2

      - name: cargo fmt
        run: cargo fmt --all -- --check
      # todo
      #- name: cargo clippy
      #  run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  test:
    name: Tests (${{ matrix.os }})
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2

      - name: cargo test
        run: cargo test --workspace --all-features

  compile:
    name: ${{ matrix.release-name || matrix.target || 'Unknown' }}
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      # todo: changed to false to test all combinations
      fail-fast: true
      matrix:
        include:
          # Example
          # when not set, default will be used (except target, cross)
          # - os: ubuntu-latest
          #   target: x86_64-unknown-linux-gnu
          #   release-name: $target
          #   toolchain: nightly
          #   tool: cargo/cross
          #   postfix: ""
          #   extra-args: ""
          #   components: ""
          #   rustflags: "--cfg tokio_unstable"

          # Linux x86 gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            tool: cross
            extra-args: -F "full"
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            postfix: ".exe"
            extra-args: -F "full"
